# Generated by Django 3.1.7 on 2021-12-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='service_pics ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewaService.category')),
            ],
        ),
    ]
