# Generated by Django 3.1.7 on 2021-12-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewaService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='service_pics'),
        ),
    ]
